In [5]:
import pandas as pd
import io

In [6]:
file_path = '/content/JSON test file.json' # set file path to variable

df = pd.read_json(file_path)

In [8]:
df.head()

,name,language,id,bio,version
0,Adeel Solangi,Sindhi,V59OF92YF627HFY0,Donec lobortis eleifend condimentum. Cras dict...,6.10
1,Afzal Ghaffar,Sindhi,ENTOCR13RSCLZ6KU,"Aliquam sollicitudin ante ligula, eget malesua...",1.88
2,Aamir Solangi,Sindhi,IAKPO3R4761JDRVG,Vestibulum pharetra libero et velit gravida eu...,7.27
3,Abla Dilmurat,Uyghur,5ZVOEPMJUI4MB4EN,Donec lobortis eleifend condimentum. Morbi ac ...,2.53
4,Adil Eli,Uyghur,6VTI8X6LL0MMPJCC,"Vivamus id faucibus velit, id posuere leo. Mor...",6.49

In [35]:
import requests

api_url = 'https://fakerapi.it/api/v2/creditCards?_quantity=500' # Define the API endpoint

response = requests.get(api_url) # Make the GET request

In [41]:
# Check if the request was successful (status code 200)
if response.status_code == 200:
    # Access the response data, typically in JSON format
    data = response.json()
    print("Data retrieved successfully:")

else:
    print(f"Failed to retrieve data. Status code: {response.status_code}")

Data retrieved successfully:

In [42]:
df = pd.DataFrame(data['data'])

              type            number expiration              owner
0       MasterCard  4168843440079963      09/28   Catalina Leannon
1       MasterCard  4556610958863728      05/28        Greta Dicki
2             Visa  4716797587763184      07/27      Norwood Doyle
3       MasterCard  5352564540417357      12/26      Ernest Pouros
4             Visa  4024007132464925      11/27      Ruth Schuster
..             ...               ...        ...                ...
495     MasterCard  4539617227777052      02/28      Shana Waelchi
496  Discover Card  3589339818776093      03/26    Reyna Langworth
497     MasterCard  5176063836744016      11/26     Rosina McGlynn
498           Visa  2438044277143273      07/28    Alanna McKenzie
499   Visa Retired  4485893938584293      12/26  Billy Cruickshank

[500 rows x 4 columns]

In [43]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df)

https://docs.google.com/spreadsheets/d/1YflgJ_yMw-XW2vlNyF_NRysgoGUrtEwwjuQJKCgIUEw/edit#gid=0